name: "JFrog OIDC Example"
on:
  workflow_dispatch:

permissions:
  id-token: write   # Required for GitHub to expose the OIDC JWT
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure JFrog CLI via OIDC
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
          JF_PROJECT: ssc-fsdh
        with:
          oidc-provider-name: setup-jfrog-cli

      - name: Run JFrog CLI commands
        run: |
          # Test the connection
          jf rt ping

          # (Optional) Collect build environment variables
          jf rt bce

          # (Optional) Collect VCS details from git
          jf rt bag

          # Publish build info (or any other build steps you need)
          jf rt bp
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
          # JFrog CLI will pick up the OIDC‐federated access token automatically,
          # no need to explicitly export JF_ACCESS_TOKEN here.
