name: "JFrog OIDC Example"
on:
  workflow_dispatch:

permissions:
  id-token: write 
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Configure JFrog CLI via OIDC
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
          JF_PROJECT: ssc-fsdh
        with:
          oidc-provider-name: github-oidc

      - name: Run JFrog CLI commands
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
        run: |
          # Test the connection
          jf rt ping

          # (Optional) Collect build environment variables
          jf rt bce

          # (Optional) Collect VCS details from git
          jf rt bag


          
