name: "JFrog OIDC Example"
on:
  push:
  workflow_dispatch:

permissions:
  id-token: write 
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch raw ID token from GitHub
        id: id-token
        uses: actions/github-script@v7
        with:
          script: |
            core.setOutput('id_token', await core.getIDToken())

      - name: Decode and display OIDC claims
        run: |
          echo "==== RAW JWT PAYLOAD ===="
          echo "${{ steps.id-token.outputs.id_token }}" \
            | cut -d "." -f2 \
            | base64 -d \
            | jq .

            
      - name: Configure JFrog CLI via OIDC
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
          JF_PROJECT: ssc-fsdh
        with:
          oidc-provider-name: setup-jfrog-cli

      - name: Run JFrog CLI commands
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
        run: |
          # Test the connection
          jf rt ping

          # (Optional) Collect build environment variables
          jf rt bce

          # (Optional) Collect VCS details from git
          jf rt bag


          