name: "JFrog Frogbot OIDC Example"
on:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write
  security-events: write
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["main"]
    steps:
      - name: Configure JFrog CLI via OIDC
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
          JF_PROJECT: ssc-fsdh
        with:
          oidc-provider-name: github-oidc

      - uses: jfrog/frogbot@v2
        with:
          oidc-provider-name: github-oidc
        env:
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}   