---
name: Trivy Code Scanning

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  trivy-scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Run Trivy Scan Action
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        with:
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          scan-type: "fs"
          format: "sarif"
          output: "trivy-results.sarif"
        env:
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true

      - name: Upload Trivy Report to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3
        with:
          sarif_file: trivy-results.sarif
